#!/usr/bin/env python

# @Author: songxiao
# @Time: 2019-08-23 10:56


class JhdReceipt:
    """销货单历史"""

    def __init__(self, url, session, assertion):
        self.url = url
        self.s = session
        self.assert_ = assertion

    @property
    def token(self):
        url = '{}/voucher/GoodsReceipt/init?user_req_id=e33e804adx16cbddd7f4c'.format(self.url)
        r = self.s.get(url)
        if self.assert_.assert_status_code(r, 200):
            return r.json().get('data').get('txnToken')

    def create_jhd(self):
        url = '{}/voucher/GoodsReceipt?user_req_id=e33e804adx16ccccf15a2'.format(self.url)
        data = {
            "data": {
                "vendorId": 706949268373505,
                "redBlueFlagEnum": "BLUE",
                "warehouseId": 703752338538497,
                "bizDate": "2019-08-26T07:21:44.157Z",
                "bizTypeId": 100101,
                "noteTypeEnum": "NORMORL_INVOICE",
                "dueDate": 1566804104157,
                "totalExtraDiscount": 0,
                "paymentList": [{
                    "salesCollectionTypeEnum": "IMMEDIATE_PAYMENT",
                    "paymentMethodTypeId": 703752339062823,
                    "finAccountId": 703752339062820,
                    "amount": 14000,
                    "editFlag": "new"
                }],
                "totalAmountWithoutTax": 14000,
                "totalAmountWithTax": 14000,
                "paymentCollectMethodEnum": "RECORD_PAYMENT_INFO",
                "totalNetAmountWithTax": 14000,
                "vRefTotalNetAmountWithTax": 14000,
                "txnToken": self.token,
                "expenseAllocationTypeEnum": None,
                "expenseNoteTypeEnum": None,
                "expenseVendorId": None,
                "goodsReceiptExpenseList": [],
                "paymentTermsEnum": "PREPAY_ALL",
                "exchangeRate": 1,
                "goodsItems": [{
                    "warehouseId": 703752338538497,
                    "itemBarcode": "",
                    "productId": 706963495452672,
                    "transUomId": 703752336310496,
                    "transQty": 100,
                    "hierarchyPkgQtysText": "100个",
                    "trans2UomId": None,
                    "baseUomId": 703752336310496,
                    "baseQty": 100,
                    "availQty": 0,
                    "availQtyHierarchyPkgText": "-",
                    "onHandQty": 0,
                    "onHandQtyHierarchyPkgText": "-",
                    "listPrice": 10,
                    "netDiscountPct": 1,
                    "netPriceWithoutTax": 10,
                    "netPriceWithTax": 10,
                    "taxPct": 0,
                    "netAmountWithoutTax": 1000,
                    "netTax": 0,
                    "netAmountWithTax": 1000,
                    "netDiscount": 0,
                    "priceWithoutTax": 10,
                    "priceWithTax": 10,
                    "amountWithoutTax": 1000,
                    "amountWithTax": 1000,
                    "costPrice": 10,
                    "costAmount": 1000,
                    "isFreeGift": False,
                    "trans2ToTransRate": None,
                    "trans2ToBaseRate": None,
                    "transToBaseRate": 1,
                    "tax": 0,
                    "sequenceNum": 0,
                    "trans2ToAuxRate": None,
                    "auxToBaseRate": None,
                    "isTransToBaseFloating": False,
                    "manualInputFlag": 536875009,
                    "isListPriceIncludingTax": False,
                    "transToAuxRate": None,
                    "netManualInputFlag": 536875009,
                    "discountPct": 1,
                    "discount": 0,
                    "refNetDiscount": 0,
                    "editFlag": "new",
                    "computing": False,
                    "copying": False,
                    "isNeedSyncCustomizedValue": False,
                    "uuid": "7",
                    "extraInWebNetGroup": {
                        "netPriceWithTax": 10,
                        "netPriceWithoutTax": 10,
                        "netAmountWithTax": 1000,
                        "netAmountWithoutTax": 1000,
                        "netDiscount": 0,
                        "netDiscountPct": 1,
                        "netTax": 0,
                        "listPrice": 10,
                        "taxPct": 0,
                        "netManualInputFlag": 536875009,
                        "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX"
                    }
                }, {
                    "warehouseId": 703752338538497,
                    "itemBarcode": "",
                    "productId": 706963629670400,
                    "transUomId": 703752336310496,
                    "transQty": 200,
                    "hierarchyPkgQtysText": "200个",
                    "trans2UomId": None,
                    "baseUomId": 703752336310496,
                    "baseQty": 200,
                    "availQty": 0,
                    "availQtyHierarchyPkgText": "-",
                    "onHandQty": 0,
                    "onHandQtyHierarchyPkgText": "-",
                    "listPrice": 20,
                    "netDiscountPct": 1,
                    "netPriceWithoutTax": 20,
                    "netPriceWithTax": 20,
                    "taxPct": 0,
                    "netAmountWithoutTax": 4000,
                    "netTax": 0,
                    "netAmountWithTax": 4000,
                    "netDiscount": 0,
                    "priceWithoutTax": 20,
                    "priceWithTax": 20,
                    "amountWithoutTax": 4000,
                    "amountWithTax": 4000,
                    "costPrice": 20,
                    "costAmount": 4000,
                    "isFreeGift": False,
                    "trans2ToTransRate": None,
                    "trans2ToBaseRate": None,
                    "transToBaseRate": 1,
                    "tax": 0,
                    "sequenceNum": 1,
                    "trans2ToAuxRate": None,
                    "auxToBaseRate": None,
                    "isTransToBaseFloating": False,
                    "manualInputFlag": 536875009,
                    "isListPriceIncludingTax": False,
                    "transToAuxRate": None,
                    "netManualInputFlag": 536875009,
                    "discountPct": 1,
                    "discount": 0,
                    "refNetDiscount": 0,
                    "editFlag": "new",
                    "computing": False,
                    "copying": False,
                    "isNeedSyncCustomizedValue": False,
                    "uuid": "8",
                    "extraInWebNetGroup": {
                        "netPriceWithTax": 20,
                        "netPriceWithoutTax": 20,
                        "netAmountWithTax": 4000,
                        "netAmountWithoutTax": 4000,
                        "netDiscount": 0,
                        "netDiscountPct": 1,
                        "netTax": 0,
                        "listPrice": 20,
                        "taxPct": 0,
                        "netManualInputFlag": 536875009,
                        "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX"
                    }
                }, {
                    "warehouseId": 703752338538497,
                    "itemBarcode": "",
                    "productId": 706963629670401,
                    "transUomId": 703752336310496,
                    "transQty": 300,
                    "hierarchyPkgQtysText": "300个",
                    "trans2UomId": None,
                    "baseUomId": 703752336310496,
                    "baseQty": 300,
                    "availQty": 0,
                    "availQtyHierarchyPkgText": "-",
                    "onHandQty": 0,
                    "onHandQtyHierarchyPkgText": "-",
                    "listPrice": 30,
                    "netDiscountPct": 1,
                    "netPriceWithoutTax": 30,
                    "netPriceWithTax": 30,
                    "taxPct": 0,
                    "netAmountWithoutTax": 9000,
                    "netTax": 0,
                    "netAmountWithTax": 9000,
                    "netDiscount": 0,
                    "priceWithoutTax": 30,
                    "priceWithTax": 30,
                    "amountWithoutTax": 9000,
                    "amountWithTax": 9000,
                    "costPrice": 30,
                    "costAmount": 9000,
                    "isFreeGift": False,
                    "trans2ToTransRate": None,
                    "trans2ToBaseRate": None,
                    "transToBaseRate": 1,
                    "tax": 0,
                    "sequenceNum": 2,
                    "trans2ToAuxRate": None,
                    "auxToBaseRate": None,
                    "isTransToBaseFloating": False,
                    "manualInputFlag": 536875009,
                    "isListPriceIncludingTax": False,
                    "transToAuxRate": None,
                    "netManualInputFlag": 536875009,
                    "discountPct": 1,
                    "discount": 0,
                    "refNetDiscount": 0,
                    "editFlag": "new",
                    "computing": False,
                    "copying": False,
                    "isNeedSyncCustomizedValue": False,
                    "uuid": "9",
                    "extraInWebNetGroup": {
                        "netPriceWithTax": 30,
                        "netPriceWithoutTax": 30,
                        "netAmountWithTax": 9000,
                        "netAmountWithoutTax": 9000,
                        "netDiscount": 0,
                        "netDiscountPct": 1,
                        "netTax": 0,
                        "listPrice": 30,
                        "taxPct": 0,
                        "netManualInputFlag": 536875009,
                        "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX"
                    }
                }],
                "voucherEntrySourceEnum": "NORMAL",
                "ignoreWarn": True,
                "id": None
            },
            "params": {}
        }
        r = self.s.post(url, json=data)
        if self.assert_.assert_status_code(r, 200):
            print('成功创建进货单，id<%s>' % r.json().get('id'))
