#!/usr/bin/env python

# @Author: songxiao
# @Time: 2019-08-21 13:43

from common.login import Login
from business.warehouse import WarehouseBusiness
from business.custvendor import CustVendor
from business.goods import Goods

login = Login()
front_url = login.url
s = login.session

# c = CustVendor(front_url, s)
# g = Goods(front_url, s)

url = 'https://inte-cloud.chanjet.com/cc/u5ik3iphbm4y/rvotwvgcwv/voucher/GoodsIssue?user_req_id=e33e804adx16cb7350814'
data = {
    "data": {
        "bizDate": 1566441212158,
        "redBlueFlagEnum": "BLUE",
        "soldToCustId": 701354939252737,
        "warehouseId": 701301657042944,
        "bizEmployeeId": 691651266084867,
        "refBoName": None,
        "departmentId": 691651266084866,
        "refVoucherCode": None,
        "srcSalesOrderId": None,
        "dueDate": 1566432000000,
        "paymentTermsEnum": "PREPAY_ALL",
        "billToCustId": 701354939252737,
        "noteTypeEnum": "NORMORL_INVOICE",
        "voucherEntrySourceEnum": "NORMAL",
        "totalAmountWithTax": 0,
        "promoList": [],
        "totalPromoDiscount": 0,
        "totalNetAmountWithTax": 0,
        "shipMethodEnum": "OTHER",
        "isStockOutImmediate": None,
        "exchangeRate": 1,
        "paymentList": [],
        "paymentCollectMethodEnum": "ON_CREDIT",
        "attachmentList": [],
        "bizTypeId": 100011,
        "txnToken": "d4XrWtsiCLKvDy+UMIsnCG23U2B0F2iE9N3rTLF9VGRc9siuRAFHSo192YZ2ANnj8zBZw85T5uY=2",
        "isCustChargedFee": None,
        "goodsItems": [{
            "warehouseId": 701301657042944,
            "itemBarcode": "",
            "productId": 701398425796608,
            "transUomId": 691651265954015,
            "transQty": 1,
            "hierarchyPkgQtysText": "1个",
            "baseUomId": 691651265954015,
            "baseQty": 1,
            "availQty": -1,
            "availQtyHierarchyPkgText": "-1个",
            "onHandQty": -1,
            "onHandQtyHierarchyPkgText": "-1个",
            "listPrice": 0,
            "netDiscountPct": 1,
            "netPriceWithoutTax": 0,
            "netPriceWithTax": 0,
            "taxPct": 0,
            "netAmountWithoutTax": 0,
            "netTax": 0,
            "netAmountWithTax": 0,
            "netDiscount": 0,
            "priceWithoutTax": 0,
            "priceWithTax": 0,
            "amountWithoutTax": 0,
            "amountWithTax": 0,
            "isFreeGift": False,
            "refBoName": None,
            "refVoucherCode": None,
            "srcSalesOrderId": None,
            "costPrice": 1.34,
            "costAmount": 1.34,
            "trans2ToTransRate": None,
            "trans2ToBaseRate": None,
            "transToBaseRate": 1,
            "tax": 0,
            "availQtyErrorMsgs": [],
            "commonErrorMsgs": [],
            "priceErrorMsgs": [],
            "sequenceNum": 0,
            "refVoucherId": None,
            "srcSalesOrderCode": None,
            "refDetailBoName": None,
            "trans2ToAuxRate": None,
            "auxToBaseRate": None,
            "isTransToBaseFloating": False,
            "manualInputFlag": 536875009,
            "hierarchyPkgQtys": {},
            "refVoucherDetailId": None,
            "isListPriceIncludingTax": False,
            "transToAuxRate": None,
            "netManualInputFlag": 536883201,
            "discountPct": 1,
            "discount": 0,
            "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX",
            "refNetDiscount": 0,
            "vGrossMargin": -1.34,
            "vGrossMarginPct": None,
            "uuid": "1",
            "editFlag": "new"
        }, {
            "warehouseId": 701301657042944,
            "itemBarcode": "",
            "productId": 701398425796609,
            "transUomId": 691651265954015,
            "transQty": 1,
            "hierarchyPkgQtysText": "1个",
            "baseUomId": 691651265954015,
            "baseQty": 1,
            "availQty": -2,
            "availQtyHierarchyPkgText": "-2个",
            "onHandQty": -2,
            "onHandQtyHierarchyPkgText": "-2个",
            "listPrice": 0,
            "netDiscountPct": 1,
            "netPriceWithoutTax": 0,
            "netPriceWithTax": 0,
            "taxPct": 0,
            "netAmountWithoutTax": 0,
            "netTax": 0,
            "netAmountWithTax": 0,
            "netDiscount": 0,
            "priceWithoutTax": 0,
            "priceWithTax": 0,
            "amountWithoutTax": 0,
            "amountWithTax": 0,
            "isFreeGift": False,
            "refBoName": None,
            "refVoucherCode": None,
            "srcSalesOrderId": None,
            "costPrice": 0,
            "costAmount": 0,
            "trans2ToTransRate": None,
            "trans2ToBaseRate": None,
            "transToBaseRate": 1,
            "tax": 0,
            "availQtyErrorMsgs": [],
            "commonErrorMsgs": [],
            "priceErrorMsgs": [],
            "sequenceNum": 1,
            "refVoucherId": None,
            "srcSalesOrderCode": None,
            "refDetailBoName": None,
            "trans2ToAuxRate": None,
            "auxToBaseRate": None,
            "isTransToBaseFloating": False,
            "manualInputFlag": 536875009,
            "hierarchyPkgQtys": {},
            "refVoucherDetailId": None,
            "isListPriceIncludingTax": False,
            "transToAuxRate": None,
            "netManualInputFlag": 536883201,
            "discountPct": 1,
            "discount": 0,
            "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX",
            "refNetDiscount": 0,
            "vGrossMargin": 0,
            "vGrossMarginPct": None,
            "uuid": "2",
            "editFlag": "new"
        }, {
            "warehouseId": 701301657042944,
            "itemBarcode": "",
            "productId": 701398425796610,
            "transUomId": 691651265954015,
            "transQty": 1,
            "hierarchyPkgQtysText": "1个",
            "baseUomId": 691651265954015,
            "baseQty": 1,
            "availQty": -4,
            "availQtyHierarchyPkgText": "-4个",
            "onHandQty": -4,
            "onHandQtyHierarchyPkgText": "-4个",
            "listPrice": 0,
            "netDiscountPct": 1,
            "netPriceWithoutTax": 0,
            "netPriceWithTax": 0,
            "taxPct": 0,
            "netAmountWithoutTax": 0,
            "netTax": 0,
            "netAmountWithTax": 0,
            "netDiscount": 0,
            "priceWithoutTax": 0,
            "priceWithTax": 0,
            "amountWithoutTax": 0,
            "amountWithTax": 0,
            "isFreeGift": False,
            "refBoName": None,
            "refVoucherCode": None,
            "srcSalesOrderId": None,
            "costPrice": 0,
            "costAmount": 0,
            "trans2ToTransRate": None,
            "trans2ToBaseRate": None,
            "transToBaseRate": 1,
            "tax": 0,
            "availQtyErrorMsgs": [],
            "commonErrorMsgs": [],
            "priceErrorMsgs": [],
            "sequenceNum": 2,
            "refVoucherId": None,
            "srcSalesOrderCode": None,
            "refDetailBoName": None,
            "trans2ToAuxRate": None,
            "auxToBaseRate": None,
            "isTransToBaseFloating": False,
            "manualInputFlag": 536875009,
            "hierarchyPkgQtys": {},
            "refVoucherDetailId": None,
            "isListPriceIncludingTax": False,
            "transToAuxRate": None,
            "netManualInputFlag": 536883201,
            "discountPct": 1,
            "discount": 0,
            "netStdPriceFlagEnum": "PRICE_WITHOUT_TAX",
            "refNetDiscount": 0,
            "vGrossMargin": 0,
            "vGrossMarginPct": None,
            "uuid": "3",
            "editFlag": "new"
        }]
    },
    "params": {
        "ignoreWarn": True
    }
}
r = s.post(url, json=data)
print(r.text)
